/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_prograii;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lfern
 */
public class PrincipalProyect extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalProyect() {
        initComponents();
        this.setLocationRelativeTo(null);
        usuarios.add(new usuario("Luis", "lfcs123", true, true, true, true, true, true));
        DefaultListModel modelo = (DefaultListModel)jl_usuarios.getModel();
        modelo.addElement(new usuario("Luis", "lfcs123", true, true, true, true, true, true));
        jl_usuarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_menuprincipal = new javax.swing.JDialog();
        pn_menu = new javax.swing.JPanel();
        lb_tituloMP = new javax.swing.JLabel();
        btn_databases = new javax.swing.JButton();
        btn_GU = new javax.swing.JButton();
        btn_modif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pn_exitMP = new javax.swing.JPanel();
        lb_exitMP = new javax.swing.JLabel();
        jd_gestionUsuarios = new javax.swing.JDialog();
        pn_GU = new javax.swing.JPanel();
        lb_tituloGU = new javax.swing.JLabel();
        lb_nombreGU = new javax.swing.JLabel();
        tf_crear = new javax.swing.JTextField();
        lb_contraGU = new javax.swing.JLabel();
        pf_crear = new javax.swing.JPasswordField();
        pn_exitGU = new javax.swing.JPanel();
        lb_exitGU = new javax.swing.JLabel();
        chb_GU = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lb_permisosGU = new javax.swing.JLabel();
        chb_create = new javax.swing.JCheckBox();
        chb_select = new javax.swing.JCheckBox();
        chb_insert = new javax.swing.JCheckBox();
        chb_delete = new javax.swing.JCheckBox();
        chb_drop = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_usuarios = new javax.swing.JList<>();
        btn_agregarUsuario = new javax.swing.JButton();
        btn_eliminarUsuario = new javax.swing.JButton();
        jd_modificarUsuario = new javax.swing.JDialog();
        pn_modificar = new javax.swing.JPanel();
        pn_exitMU = new javax.swing.JPanel();
        lb_exitMU = new javax.swing.JLabel();
        lb_tituloMU = new javax.swing.JLabel();
        lb_nombreMU = new javax.swing.JLabel();
        lb_contraMU = new javax.swing.JLabel();
        tf_modificar = new javax.swing.JTextField();
        pf_modificar = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        img_MU = new javax.swing.JLabel();
        btn_modificarU = new javax.swing.JButton();
        jd_databases = new javax.swing.JDialog();
        pn_DB = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_db = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_SQL = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtable_db = new javax.swing.JTable();
        lb_tituloDB = new javax.swing.JLabel();
        btn_ejecutar = new javax.swing.JButton();
        lb_sql = new javax.swing.JLabel();
        pn_exitDB = new javax.swing.JPanel();
        lb_exitDB = new javax.swing.JLabel();
        jp_is = new javax.swing.JPanel();
        lb_tituloIS = new javax.swing.JLabel();
        lb_nombreIS = new javax.swing.JLabel();
        lb_passwordIS = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pf_contraIS = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        bttn_entrar = new javax.swing.JButton();
        tf_nombreIS = new javax.swing.JTextField();
        img_IS1 = new javax.swing.JLabel();
        pn_exitIS = new javax.swing.JPanel();
        lb_exitIS = new javax.swing.JLabel();

        jd_menuprincipal.setUndecorated(true);
        jd_menuprincipal.setResizable(false);

        lb_tituloMP.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb_tituloMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloMP.setText("MENU PRINCIPAL");

        btn_databases.setBackground(new java.awt.Color(204, 0, 102));
        btn_databases.setForeground(new java.awt.Color(0, 0, 0));
        btn_databases.setText("Mis Databases");
        btn_databases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_databasesMouseClicked(evt);
            }
        });

        btn_GU.setBackground(new java.awt.Color(255, 153, 153));
        btn_GU.setForeground(new java.awt.Color(0, 0, 0));
        btn_GU.setText("Gestion de Usuarios");
        btn_GU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GUMouseClicked(evt);
            }
        });

        btn_modif.setBackground(new java.awt.Color(255, 51, 102));
        btn_modif.setForeground(new java.awt.Color(0, 0, 0));
        btn_modif.setText("Modificar mi Usuario");
        btn_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modifMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lfern\\OneDrive\\Imágenes\\Que-es-una-Base-de-Datos_Latam-Dominios.jpg")); // NOI18N

        pn_exitMP.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitMP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exitMP.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitMP.setText("X");
        lb_exitMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitMPLayout = new javax.swing.GroupLayout(pn_exitMP);
        pn_exitMP.setLayout(pn_exitMPLayout);
        pn_exitMPLayout.setHorizontalGroup(
            pn_exitMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        pn_exitMPLayout.setVerticalGroup(
            pn_exitMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_tituloMP, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_GU, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_databases, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(pn_menuLayout.createSequentialGroup()
                        .addComponent(pn_exitMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addComponent(pn_exitMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lb_tituloMP)
                .addGap(49, 49, 49)
                .addComponent(btn_GU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btn_databases, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_menuprincipalLayout = new javax.swing.GroupLayout(jd_menuprincipal.getContentPane());
        jd_menuprincipal.getContentPane().setLayout(jd_menuprincipalLayout);
        jd_menuprincipalLayout.setHorizontalGroup(
            jd_menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_menuprincipalLayout.setVerticalGroup(
            jd_menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_gestionUsuarios.setUndecorated(true);
        jd_gestionUsuarios.setResizable(false);
        jd_gestionUsuarios.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_tituloGU.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lb_tituloGU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloGU.setText("Gestion de Usuarios");

        lb_nombreGU.setText("Nombre");

        lb_contraGU.setText("Contraseña");

        pn_exitGU.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitGU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_exitGU.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitGU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitGU.setText("X");
        lb_exitGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitGUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitGUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitGUMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitGULayout = new javax.swing.GroupLayout(pn_exitGU);
        pn_exitGU.setLayout(pn_exitGULayout);
        pn_exitGULayout.setHorizontalGroup(
            pn_exitGULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitGU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        pn_exitGULayout.setVerticalGroup(
            pn_exitGULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitGU, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        chb_GU.setText("Gestionar Usuarios");

        lb_permisosGU.setText("Permisos de Usuario de Menu Principal");

        chb_create.setText("Create");

        chb_select.setText("Select");

        chb_insert.setText("Insert/Consulta");

        chb_delete.setText("Delete");

        chb_drop.setText("Drop");

        jl_usuarios.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_usuarios);

        btn_agregarUsuario.setText("Agregar Usuario");
        btn_agregarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarUsuarioMouseClicked(evt);
            }
        });

        btn_eliminarUsuario.setText("Eliminar Usuario");
        btn_eliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_GULayout = new javax.swing.GroupLayout(pn_GU);
        pn_GU.setLayout(pn_GULayout);
        pn_GULayout.setHorizontalGroup(
            pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GULayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lb_tituloGU, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(pn_exitGU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(pn_GULayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_GULayout.createSequentialGroup()
                        .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chb_GU, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_GULayout.createSequentialGroup()
                                .addComponent(chb_select, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(chb_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(pn_GULayout.createSequentialGroup()
                        .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nombreGU, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_contraGU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pn_GULayout.createSequentialGroup()
                                    .addComponent(chb_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chb_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chb_create, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_permisosGU, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pf_crear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                            .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_crear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pn_GULayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btn_agregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        pn_GULayout.setVerticalGroup(
            pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GULayout.createSequentialGroup()
                .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_GULayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_tituloGU))
                    .addComponent(pn_exitGU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_nombreGU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_GULayout.createSequentialGroup()
                        .addComponent(tf_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lb_contraGU)
                        .addGap(18, 18, 18)
                        .addComponent(pf_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_permisosGU)
                        .addGap(20, 20, 20)
                        .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_GU)
                            .addComponent(chb_create))
                        .addGap(18, 18, 18)
                        .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_select)
                            .addComponent(chb_insert))
                        .addGap(18, 18, 18)
                        .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_delete)
                            .addComponent(chb_drop)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pn_GULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jd_gestionUsuarios.getContentPane().add(pn_GU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_modificarUsuario.setUndecorated(true);
        jd_modificarUsuario.setResizable(false);
        jd_modificarUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_exitMU.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitMU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exitMU.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitMU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitMU.setText("X");
        lb_exitMU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMUMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitMULayout = new javax.swing.GroupLayout(pn_exitMU);
        pn_exitMU.setLayout(pn_exitMULayout);
        pn_exitMULayout.setHorizontalGroup(
            pn_exitMULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitMU, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );
        pn_exitMULayout.setVerticalGroup(
            pn_exitMULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitMU, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        lb_tituloMU.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb_tituloMU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloMU.setText("Modificar Mi Usuario");

        lb_nombreMU.setText("Nuevo nombre");

        lb_contraMU.setText("Nueva contraseña");

        img_MU.setIcon(new javax.swing.ImageIcon("C:\\Users\\lfern\\OneDrive\\Imágenes\\usobasedatos-768x432.jpg")); // NOI18N

        btn_modificarU.setText("Modificar");
        btn_modificarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_modificarLayout = new javax.swing.GroupLayout(pn_modificar);
        pn_modificar.setLayout(pn_modificarLayout);
        pn_modificarLayout.setHorizontalGroup(
            pn_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_modificarLayout.createSequentialGroup()
                .addGroup(pn_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_modificarLayout.createSequentialGroup()
                        .addComponent(pn_exitMU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_tituloMU, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_modificarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pn_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nombreMU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_contraMU, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_modificarLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_modificarU, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_MU, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        pn_modificarLayout.setVerticalGroup(
            pn_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_modificarLayout.createSequentialGroup()
                .addGroup(pn_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_exitMU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_tituloMU)))
                .addGap(18, 18, 18)
                .addComponent(lb_nombreMU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_contraMU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pf_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificarU, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(img_MU, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jd_modificarUsuario.getContentPane().add(pn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        jd_databases.setUndecorated(true);
        jd_databases.setResizable(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Databases");
        jt_db.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_db);

        ta_SQL.setColumns(20);
        ta_SQL.setRows(5);
        jScrollPane3.setViewportView(ta_SQL);

        jtable_db.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtable_db);

        lb_tituloDB.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb_tituloDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloDB.setText("Mis Databases");

        btn_ejecutar.setText("Ejecutar Comando SQL");

        lb_sql.setText("SQL");

        pn_exitDB.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exitDB.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitDB.setText("X");
        lb_exitDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitDBMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitDBLayout = new javax.swing.GroupLayout(pn_exitDB);
        pn_exitDB.setLayout(pn_exitDBLayout);
        pn_exitDBLayout.setHorizontalGroup(
            pn_exitDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_exitDBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_exitDB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_exitDBLayout.setVerticalGroup(
            pn_exitDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitDB, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_DBLayout = new javax.swing.GroupLayout(pn_DB);
        pn_DB.setLayout(pn_DBLayout);
        pn_DBLayout.setHorizontalGroup(
            pn_DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_DBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_DBLayout.createSequentialGroup()
                        .addGroup(pn_DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(pn_DBLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lb_tituloDB, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_exitDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_DBLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lb_sql, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        pn_DBLayout.setVerticalGroup(
            pn_DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_DBLayout.createSequentialGroup()
                .addGroup(pn_DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_DBLayout.createSequentialGroup()
                        .addComponent(lb_tituloDB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(pn_DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_sql)
                            .addComponent(btn_ejecutar)))
                    .addComponent(pn_exitDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(pn_DBLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_databasesLayout = new javax.swing.GroupLayout(jd_databases.getContentPane());
        jd_databases.getContentPane().setLayout(jd_databasesLayout);
        jd_databasesLayout.setHorizontalGroup(
            jd_databasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_DB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_databasesLayout.setVerticalGroup(
            jd_databasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_DB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_tituloIS.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb_tituloIS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloIS.setText("Iniciar Sesion");

        lb_nombreIS.setText("Nombre");

        lb_passwordIS.setText("Contraseña");

        bttn_entrar.setText("Entrar");
        bttn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttn_entrarMouseClicked(evt);
            }
        });

        img_IS1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lfern\\OneDrive\\Imágenes\\Álbum de cámara\\databases.jpg")); // NOI18N

        pn_exitIS.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitIS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exitIS.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitIS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitIS.setText("X");
        lb_exitIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitISMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitISMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitISMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitISLayout = new javax.swing.GroupLayout(pn_exitIS);
        pn_exitIS.setLayout(pn_exitISLayout);
        pn_exitISLayout.setHorizontalGroup(
            pn_exitISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitIS, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
        pn_exitISLayout.setVerticalGroup(
            pn_exitISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_isLayout = new javax.swing.GroupLayout(jp_is);
        jp_is.setLayout(jp_isLayout);
        jp_isLayout.setHorizontalGroup(
            jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_isLayout.createSequentialGroup()
                .addComponent(img_IS1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_isLayout.createSequentialGroup()
                        .addGroup(jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_isLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_passwordIS, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_isLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(bttn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(jp_isLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lb_tituloIS, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_isLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_exitIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jp_isLayout.setVerticalGroup(
            jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_isLayout.createSequentialGroup()
                .addComponent(pn_exitIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lb_tituloIS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_nombreIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_passwordIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(bttn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_isLayout.createSequentialGroup()
                .addComponent(img_IS1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jp_is, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn_entrarMouseClicked
        // TODO add your handling code here:
        
        AdmUsuario am = new AdmUsuario("./usuarios/"+tf_nombreIS.getText()+".txt");
        try {
            am.cargarArchivo();
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this, "Este archivo no existe!");
        }
        int cont = 0;
        
        for (int i = 0; i < am.listaUsuarios.size(); i++) {
            if(tf_nombreIS.getText().equals(am.listaUsuarios.get(i).getNombre())&&pf_contraIS.getText().equals(am.listaUsuarios.get(i).getContra())){
                cont = 1;
                //System.out.println(cont);
                u_seleccionado = (usuario)usuarios.get(i);
                index_usuario_actual = i;
                FileSeleccionado = "./usuarios/"+tf_nombreIS.getText()+".txt";
            }else{
                cont = 0;
            }
        }
        

        if(cont == 1){
            abreMenuPrincipal();
        }else{
            JOptionPane.showMessageDialog(this, "Usuario no existe.");
        }
        tf_nombreIS.setText("");
        pf_contraIS.setText("");
    }//GEN-LAST:event_bttn_entrarMouseClicked

    private void lb_exitISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitISMouseClicked
        // TODO add your handling code here:
        String nombre = "Luis";
        String contra = "lfcs123";
        AdmUsuario am = new AdmUsuario(FileSeleccionado);
        try {
            am.cargarArchivo();
        } catch (IOException ex) {
            
        }
        
        for (usuario User : am.getListaUsuarios()) {
            User.setNombre(nombre);
            User.setContra(contra);
        }
        try {
            am.escribirArchivo();
        } catch (IOException ex) {
            
        }
        File archivoantiguo = new File(FileSeleccionado);
        File archivonuevonombre = new File("./usuarios/"+nombre+".txt");
        boolean renombrado = archivoantiguo.renameTo(archivonuevonombre);
        if(renombrado){
            
        }else{
            
        }
        System.exit(0);
    }//GEN-LAST:event_lb_exitISMouseClicked

    private void lb_exitISMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitISMouseEntered
        // TODO add your handling code here:
        pn_exitIS.setBackground(Color.red);
        lb_exitIS.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitISMouseEntered

    private void lb_exitISMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitISMouseExited
        // TODO add your handling code here:
        pn_exitIS.setBackground(Color.white);
        lb_exitIS.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitISMouseExited

    private void lb_exitMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMPMouseClicked
        // TODO add your handling code here:
        jd_menuprincipal.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_lb_exitMPMouseClicked

    private void lb_exitMPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMPMouseEntered
        // TODO add your handling code here:
        pn_exitMP.setBackground(Color.red);
        lb_exitMP.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMPMouseEntered

    private void lb_exitMPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMPMouseExited
        // TODO add your handling code here:
        pn_exitMP.setBackground(Color.white);
        lb_exitMP.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitMPMouseExited

    private void lb_exitGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitGUMouseClicked
        // TODO add your handling code here:
        jd_gestionUsuarios.setVisible(false);
        jd_menuprincipal.setVisible(true);
        
    }//GEN-LAST:event_lb_exitGUMouseClicked

    private void lb_exitGUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitGUMouseEntered
        // TODO add your handling code here:
        pn_exitGU.setBackground(Color.red);
        lb_exitGU.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitGUMouseEntered

    private void lb_exitGUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitGUMouseExited
        // TODO add your handling code here:
        pn_exitGU.setBackground(Color.white);
        lb_exitGU.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitGUMouseExited

    private void btn_agregarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarUsuarioMouseClicked
        // TODO add your handling code here:
        
        try {
            String nombre = tf_crear.getText();
            String contra = pf_crear.getText();
            boolean gestionU = false;
            if(chb_GU.isSelected()){
                gestionU = true;
            }
            boolean create = false;
            if(chb_create.isSelected()){
                create = true;
            }
            boolean select = false;
            if(chb_select.isSelected()){
                select = true;
            }
            boolean insert = false;
            if(chb_insert.isSelected()){
                insert = true;
            }
            boolean delete = false;
            if(chb_delete.isSelected()){
                delete = true;
            }
            boolean drop = false;
            if(chb_drop.isSelected()){
                drop = true;
            }
            usuarios.add(new usuario(nombre, contra, gestionU, create, select, insert, delete, drop));
            DefaultListModel m = (DefaultListModel)jl_usuarios.getModel();
            m.addElement(new usuario(nombre, contra, gestionU, create, select, insert, delete, drop));
            jl_usuarios.setModel(m);
            tf_crear.setText("");
            pf_crear.setText("");
            chb_GU.setSelected(false);
            chb_create.setSelected(false);
            chb_delete.setSelected(false);
            chb_drop.setSelected(false);
            chb_insert.setSelected(false);
            chb_select.setSelected(false);
            AdmUsuario am = new AdmUsuario("./usuarios/"+nombre+".txt");
            am.listaUsuarios.add(new usuario(nombre, contra, gestionU, create, select, insert, delete, drop));
            am.escribirArchivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_gestionUsuarios, "No se ha podido agregar usuario.");
        }
    }//GEN-LAST:event_btn_agregarUsuarioMouseClicked

    private void btn_eliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMouseClicked
        // TODO add your handling code here:
        if(jl_usuarios.getSelectedIndex()>=0){
            
            DefaultListModel m = (DefaultListModel) jl_usuarios.getModel();
            int index = jl_usuarios.getSelectedIndex();
            u_eliminar = (usuario)m.get(index);
            m.remove(index);
            jl_usuarios.setModel(m);
            for (int i = 0; i < usuarios.size(); i++) {
                if(usuarios.get(i).getNombre().equals(u_eliminar.getNombre())&& usuarios.get(i).getContra().equals(u_eliminar.getContra())){
                    usuarios.remove(i);
                    break;
                } 
            }
            File eliminar = new File("./usuarios/"+u_eliminar.getNombre()+".txt");
            if(eliminar.exists()){
                boolean eliminado = eliminar.delete();
                if(eliminado){
                    JOptionPane.showMessageDialog(jd_gestionUsuarios, "Se ha eliminado exitosamente!");
                }else{
                   JOptionPane.showMessageDialog(jd_gestionUsuarios, "No se ha podido eliminar!");
                }
            }else{
                JOptionPane.showMessageDialog(jd_gestionUsuarios, "No existe el archivo!");
            }
        }
    }//GEN-LAST:event_btn_eliminarUsuarioMouseClicked

    private void btn_GUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GUMouseClicked
        // TODO add your handling code here:
        AdmUsuario am = new AdmUsuario(FileSeleccionado);
        boolean gestionarU = false;
        try {
            am.cargarArchivo();
        } catch (IOException ex) {
            
        }
        for (usuario user : am.getListaUsuarios()) {
            gestionarU = user.gestionU;
        }
        
        if(gestionarU==false){
            JOptionPane.showMessageDialog(jd_menuprincipal, "Este usuario no tiene permisos para gestionar usuarios!");
        }else{
           abreGestionUsuarios(); 
        }
    }//GEN-LAST:event_btn_GUMouseClicked

    private void lb_exitMUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMUMouseClicked
        // TODO add your handling code here:
        jd_menuprincipal.setVisible(true);
        jd_modificarUsuario.setVisible(false);
    }//GEN-LAST:event_lb_exitMUMouseClicked

    private void lb_exitMUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMUMouseEntered
        // TODO add your handling code here:
        pn_exitMU.setBackground(Color.red);
        lb_exitMU.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMUMouseEntered

    private void lb_exitMUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMUMouseExited
        // TODO add your handling code here:
        pn_exitMU.setBackground(Color.white);
        lb_exitMU.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitMUMouseExited

    private void btn_modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modifMouseClicked
        // TODO add your handling code here:
        abreModificarUsuario();
    }//GEN-LAST:event_btn_modifMouseClicked

    private void btn_modificarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarUMouseClicked
        // TODO add your handling code here:
        AdmUsuario am = new AdmUsuario(FileSeleccionado);
        try {
            am.cargarArchivo();
        } catch (IOException ex) {
            
        }
        String nuevo_nombre = tf_modificar.getText();
        String nueva_contra = pf_modificar.getText();
        for (usuario User : am.getListaUsuarios()) {
            User.setNombre(nuevo_nombre);
            User.setContra(nueva_contra);
        }
        try {
            am.escribirArchivo();
        } catch (IOException ex) {
            
        }
        File archivoantiguo = new File(FileSeleccionado);
        File archivonuevonombre = new File("./usuarios/"+nuevo_nombre+".txt");
        boolean renombrado = archivoantiguo.renameTo(archivonuevonombre);
        if(renombrado){
            JOptionPane.showMessageDialog(jd_modificarUsuario, "Se ha modificado exitosamente.");
        }else{
            JOptionPane.showMessageDialog(jd_modificarUsuario, "No se ha podido modificar!");
        }
        FileSeleccionado = "./usuarios/"+nuevo_nombre+".txt";
        
        usuarios.get(index_usuario_actual).setNombre(nuevo_nombre);
        usuarios.get(index_usuario_actual).setContra(nueva_contra);
        
        DefaultListModel m = (DefaultListModel)jl_usuarios.getModel();
        ((usuario)m.get(index_usuario_actual)).setNombre(nuevo_nombre);
        ((usuario)m.get(index_usuario_actual)).setContra(nueva_contra);
        jl_usuarios.setModel(m);
        tf_modificar.setText("");
        pf_modificar.setText("");
    }//GEN-LAST:event_btn_modificarUMouseClicked

    private void lb_exitDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitDBMouseClicked
        // TODO add your handling code here:
        jd_menuprincipal.setVisible(true);
        jd_databases.setVisible(false);
    }//GEN-LAST:event_lb_exitDBMouseClicked

    private void lb_exitDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitDBMouseEntered
        // TODO add your handling code here:
        pn_exitDB.setBackground(Color.red);
        lb_exitDB.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitDBMouseEntered

    private void lb_exitDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitDBMouseExited
        // TODO add your handling code here:
        pn_exitDB.setBackground(Color.white);
        lb_exitDB.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitDBMouseExited

    private void btn_databasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_databasesMouseClicked
        // TODO add your handling code here:
        abreDatabase();
    }//GEN-LAST:event_btn_databasesMouseClicked
    
    public void abreMenuPrincipal(){
        jd_menuprincipal.pack();
        jd_menuprincipal.setModal(true);
        jd_menuprincipal.setLocationRelativeTo(this);
        jd_menuprincipal.setVisible(true);
    }
    public void abreGestionUsuarios(){
        jd_gestionUsuarios.pack();
        jd_gestionUsuarios.setModal(true);
        jd_gestionUsuarios.setLocationRelativeTo(jd_menuprincipal);
        jd_gestionUsuarios.setVisible(true);
    }
    
    public void abreModificarUsuario(){
        jd_modificarUsuario.pack();
        jd_modificarUsuario.setModal(true);
        jd_modificarUsuario.setLocationRelativeTo(jd_menuprincipal);
        jd_modificarUsuario.setVisible(true);
    }
    public void abreDatabase(){
        jd_databases.pack();
        jd_databases.setModal(true);
        jd_databases.setLocationRelativeTo(jd_menuprincipal);
        jd_databases.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalProyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GU;
    private javax.swing.JButton btn_agregarUsuario;
    private javax.swing.JButton btn_databases;
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_eliminarUsuario;
    private javax.swing.JButton btn_modif;
    private javax.swing.JButton btn_modificarU;
    private javax.swing.JButton bttn_entrar;
    private javax.swing.JCheckBox chb_GU;
    private javax.swing.JCheckBox chb_create;
    private javax.swing.JCheckBox chb_delete;
    private javax.swing.JCheckBox chb_drop;
    private javax.swing.JCheckBox chb_insert;
    private javax.swing.JCheckBox chb_select;
    private javax.swing.JLabel img_IS1;
    private javax.swing.JLabel img_MU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JDialog jd_databases;
    private javax.swing.JDialog jd_gestionUsuarios;
    private javax.swing.JDialog jd_menuprincipal;
    private javax.swing.JDialog jd_modificarUsuario;
    private javax.swing.JList<String> jl_usuarios;
    private javax.swing.JPanel jp_is;
    private javax.swing.JTree jt_db;
    private javax.swing.JTable jtable_db;
    private javax.swing.JLabel lb_contraGU;
    private javax.swing.JLabel lb_contraMU;
    private javax.swing.JLabel lb_exitDB;
    private javax.swing.JLabel lb_exitGU;
    private javax.swing.JLabel lb_exitIS;
    private javax.swing.JLabel lb_exitMP;
    private javax.swing.JLabel lb_exitMU;
    private javax.swing.JLabel lb_nombreGU;
    private javax.swing.JLabel lb_nombreIS;
    private javax.swing.JLabel lb_nombreMU;
    private javax.swing.JLabel lb_passwordIS;
    private javax.swing.JLabel lb_permisosGU;
    private javax.swing.JLabel lb_sql;
    private javax.swing.JLabel lb_tituloDB;
    private javax.swing.JLabel lb_tituloGU;
    private javax.swing.JLabel lb_tituloIS;
    private javax.swing.JLabel lb_tituloMP;
    private javax.swing.JLabel lb_tituloMU;
    private javax.swing.JPasswordField pf_contraIS;
    private javax.swing.JPasswordField pf_crear;
    private javax.swing.JPasswordField pf_modificar;
    private javax.swing.JPanel pn_DB;
    private javax.swing.JPanel pn_GU;
    private javax.swing.JPanel pn_exitDB;
    private javax.swing.JPanel pn_exitGU;
    private javax.swing.JPanel pn_exitIS;
    private javax.swing.JPanel pn_exitMP;
    private javax.swing.JPanel pn_exitMU;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_modificar;
    private javax.swing.JTextArea ta_SQL;
    private javax.swing.JTextField tf_crear;
    private javax.swing.JTextField tf_modificar;
    private javax.swing.JTextField tf_nombreIS;
    // End of variables declaration//GEN-END:variables
    public ArrayList<usuario> usuarios = new ArrayList();
    usuario u_seleccionado;
    usuario u_eliminar;
    int index_usuario_actual;
    String FileSeleccionado;
}
