/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_prograii;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lfern
 */
public class PrincipalProyect extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalProyect() {
        initComponents();
        this.setLocationRelativeTo(null);
        usuarios.add(new usuario("Luis", "lfcs123", true, true, true, true, true, true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_menuprincipal = new javax.swing.JDialog();
        pn_menu = new javax.swing.JPanel();
        lb_tituloMP = new javax.swing.JLabel();
        btn_databases = new javax.swing.JButton();
        btn_GU = new javax.swing.JButton();
        btn_modif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pn_exitMP = new javax.swing.JPanel();
        lb_exitMP = new javax.swing.JLabel();
        jd_gestionUsuarios = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jp_is = new javax.swing.JPanel();
        lb_tituloIS = new javax.swing.JLabel();
        lb_nombreIS = new javax.swing.JLabel();
        lb_passwordIS = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pf_contraIS = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        bttn_entrar = new javax.swing.JButton();
        tf_nombreIS = new javax.swing.JTextField();
        img_IS1 = new javax.swing.JLabel();
        pn_exitIS = new javax.swing.JPanel();
        lb_exitIS = new javax.swing.JLabel();

        jd_menuprincipal.setUndecorated(true);
        jd_menuprincipal.setResizable(false);

        lb_tituloMP.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb_tituloMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloMP.setText("MENU PRINCIPAL");

        btn_databases.setBackground(new java.awt.Color(204, 0, 102));
        btn_databases.setForeground(new java.awt.Color(0, 0, 0));
        btn_databases.setText("Mis Databases");

        btn_GU.setBackground(new java.awt.Color(255, 153, 153));
        btn_GU.setForeground(new java.awt.Color(0, 0, 0));
        btn_GU.setText("Gestion de Usuarios");

        btn_modif.setBackground(new java.awt.Color(255, 51, 102));
        btn_modif.setForeground(new java.awt.Color(0, 0, 0));
        btn_modif.setText("Modificar mi Usuario");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lfern\\OneDrive\\Imágenes\\Que-es-una-Base-de-Datos_Latam-Dominios.jpg")); // NOI18N

        pn_exitMP.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitMP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exitMP.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitMP.setText("X");
        lb_exitMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitMPLayout = new javax.swing.GroupLayout(pn_exitMP);
        pn_exitMP.setLayout(pn_exitMPLayout);
        pn_exitMPLayout.setHorizontalGroup(
            pn_exitMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        pn_exitMPLayout.setVerticalGroup(
            pn_exitMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_tituloMP, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_GU, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_databases, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(pn_menuLayout.createSequentialGroup()
                        .addComponent(pn_exitMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addComponent(pn_exitMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lb_tituloMP)
                .addGap(49, 49, 49)
                .addComponent(btn_GU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btn_databases, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_menuprincipalLayout = new javax.swing.GroupLayout(jd_menuprincipal.getContentPane());
        jd_menuprincipal.getContentPane().setLayout(jd_menuprincipalLayout);
        jd_menuprincipalLayout.setHorizontalGroup(
            jd_menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_menuprincipalLayout.setVerticalGroup(
            jd_menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_gestionUsuariosLayout = new javax.swing.GroupLayout(jd_gestionUsuarios.getContentPane());
        jd_gestionUsuarios.getContentPane().setLayout(jd_gestionUsuariosLayout);
        jd_gestionUsuariosLayout.setHorizontalGroup(
            jd_gestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_gestionUsuariosLayout.setVerticalGroup(
            jd_gestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_tituloIS.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb_tituloIS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloIS.setText("Iniciar Sesion");

        lb_nombreIS.setText("Nombre");

        lb_passwordIS.setText("Contraseña");

        bttn_entrar.setText("Entrar");
        bttn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttn_entrarMouseClicked(evt);
            }
        });

        img_IS1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lfern\\OneDrive\\Imágenes\\Álbum de cámara\\databases.jpg")); // NOI18N

        pn_exitIS.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitIS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exitIS.setForeground(new java.awt.Color(0, 0, 0));
        lb_exitIS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitIS.setText("X");
        lb_exitIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitISMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitISMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitISMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitISLayout = new javax.swing.GroupLayout(pn_exitIS);
        pn_exitIS.setLayout(pn_exitISLayout);
        pn_exitISLayout.setHorizontalGroup(
            pn_exitISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitIS, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
        pn_exitISLayout.setVerticalGroup(
            pn_exitISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_isLayout = new javax.swing.GroupLayout(jp_is);
        jp_is.setLayout(jp_isLayout);
        jp_isLayout.setHorizontalGroup(
            jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_isLayout.createSequentialGroup()
                .addComponent(img_IS1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_isLayout.createSequentialGroup()
                        .addGroup(jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_isLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_passwordIS, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_isLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(bttn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(jp_isLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lb_tituloIS, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_isLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_exitIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jp_isLayout.setVerticalGroup(
            jp_isLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_isLayout.createSequentialGroup()
                .addComponent(pn_exitIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lb_tituloIS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_nombreIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_passwordIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(bttn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_isLayout.createSequentialGroup()
                .addComponent(img_IS1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jp_is, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn_entrarMouseClicked
        // TODO add your handling code here:
        int cont = 0;
        for (int i = 0; i < usuarios.size(); i++) {
            if(tf_nombreIS.getText().equals(((usuario)usuarios.get(i)).getNombre())&&pf_contraIS.getText().equals(((usuario)usuarios.get(i)).getContra())){
                cont = 1;
                u_seleccionado = (usuario)usuarios.get(i);
            }else{
                cont = 0;
            }
        }
        
        if(cont == 1){
            abreMenuPrincipal();
        }else{
            JOptionPane.showMessageDialog(this, "Usuario no existe.");
        }
        tf_nombreIS.setText("");
        pf_contraIS.setText("");
    }//GEN-LAST:event_bttn_entrarMouseClicked

    private void lb_exitISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitISMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lb_exitISMouseClicked

    private void lb_exitISMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitISMouseEntered
        // TODO add your handling code here:
        pn_exitIS.setBackground(Color.red);
        lb_exitIS.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitISMouseEntered

    private void lb_exitISMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitISMouseExited
        // TODO add your handling code here:
        pn_exitIS.setBackground(Color.white);
        lb_exitIS.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitISMouseExited

    private void lb_exitMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMPMouseClicked
        // TODO add your handling code here:
        jd_menuprincipal.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_lb_exitMPMouseClicked

    private void lb_exitMPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMPMouseEntered
        // TODO add your handling code here:
        pn_exitMP.setBackground(Color.red);
        lb_exitMP.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMPMouseEntered

    private void lb_exitMPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMPMouseExited
        // TODO add your handling code here:
        pn_exitMP.setBackground(Color.white);
        lb_exitMP.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitMPMouseExited
    
    private void abreMenuPrincipal(){
        jd_menuprincipal.pack();
        jd_menuprincipal.setModal(true);
        jd_menuprincipal.setLocationRelativeTo(this);
        jd_menuprincipal.setVisible(true);
    }
    private void abreGestionUsuarios(){
        jd_gestionUsuarios.pack();
        jd_gestionUsuarios.setModal(true);
        jd_gestionUsuarios.setLocationRelativeTo(this);
        jd_gestionUsuarios.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalProyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GU;
    private javax.swing.JButton btn_databases;
    private javax.swing.JButton btn_modif;
    private javax.swing.JButton bttn_entrar;
    private javax.swing.JLabel img_IS1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JDialog jd_gestionUsuarios;
    private javax.swing.JDialog jd_menuprincipal;
    private javax.swing.JPanel jp_is;
    private javax.swing.JLabel lb_exitIS;
    private javax.swing.JLabel lb_exitMP;
    private javax.swing.JLabel lb_nombreIS;
    private javax.swing.JLabel lb_passwordIS;
    private javax.swing.JLabel lb_tituloIS;
    private javax.swing.JLabel lb_tituloMP;
    private javax.swing.JPasswordField pf_contraIS;
    private javax.swing.JPanel pn_exitIS;
    private javax.swing.JPanel pn_exitMP;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JTextField tf_nombreIS;
    // End of variables declaration//GEN-END:variables
    public ArrayList<usuario> usuarios = new ArrayList();
    usuario u_seleccionado;
}
